'use client'

import Link from 'next/link'
import { FormEvent, useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'

export default function ResetPasswordPage() {
  const router = useRouter(); const [password, setPassword] = useState(''); const [confirmPassword, setConfirmPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const [ready, setReady] = useState(false)
  useEffect(() => { const supabase = createClient(); supabase.auth.getSession().then(({ data }) => setReady(Boolean(data.session))) }, [])
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); if (password.length < 6) { setError('Choose a password with at least 6 characters.'); return }; if (password !== confirmPassword) { setError('Passwords do not match.'); return }; setLoading(true); const { error: updateError } = await createClient().auth.updateUser({ password }); if (updateError) { setError(updateError.message.toLowerCase().includes('password') ? 'Choose a stronger password.' : 'Unable to update your password. Please request a new reset link.'); setLoading(false); return }; await createClient().auth.signOut(); router.replace('/auth/login?reset=success') }
  return <main className="flex min-h-screen items-center justify-center bg-background px-5 py-10 text-foreground"><section className="w-full max-w-md rounded-2xl border border-border bg-card p-7 shadow-sm"><div className="mb-8 flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-xl bg-primary text-primary-foreground">S</div><span className="font-semibold">StudyBuddy</span></div><h1 className="text-3xl font-bold tracking-tight">Choose a new password</h1><p className="mt-2 text-sm text-muted-foreground">Use a secure password you have not used elsewhere.</p>{ready ? <form onSubmit={submit} className="mt-7 flex flex-col gap-4"><label className="flex flex-col gap-2 text-sm font-medium" htmlFor="password">New password<input id="password" name="password" type="password" autoComplete="new-password" minLength={6} required value={password} onChange={(e) => setPassword(e.target.value)} className="rounded-xl border border-input bg-background px-4 py-3 outline-none focus:border-primary" /></label><label className="flex flex-col gap-2 text-sm font-medium" htmlFor="confirm-password">Confirm new password<input id="confirm-password" name="confirm-password" type="password" autoComplete="new-password" minLength={6} required value={confirmPassword} onChange={(e) => setConfirmPassword(e.target.value)} className="rounded-xl border border-input bg-background px-4 py-3 outline-none focus:border-primary" /></label>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<button type="submit" disabled={loading} className="rounded-xl bg-primary py-3 font-semibold text-primary-foreground disabled:opacity-50">{loading ? 'Updating…' : 'Update password'}</button></form> : <p role="alert" className="mt-7 text-sm text-destructive">This reset link is invalid or expired. Request a new one.</p>}<p className="mt-6 text-center text-sm text-muted-foreground"><Link href="/auth/forgot-password" className="font-semibold text-primary hover:underline">Request a new reset link</Link></p></section></main>
}
