'use client'

import Link from 'next/link'
import { useState } from 'react'
import {
  ArrowRight, BrainCircuit, Check, ChevronDown, CircleHelp, FileQuestion,
  Languages, Menu, MessageCircle, Play, Sparkles, Target, Trophy, Upload, X, Zap,
} from 'lucide-react'

const faqs = [
  ['What is StudyBuddy?', 'StudyBuddy is an AI study companion that helps you understand questions, practice with quizzes, and turn difficult topics into useful notes.'],
  ['Who is StudyBuddy for?', 'It is built for SSC, HSC, and university students who want clearer explanations and more confident study sessions.'],
  ['Can I upload a screenshot?', 'Yes. The question solver supports screenshot-based questions so you can start from the problem already in front of you.'],
  ['Can StudyBuddy explain things in Bangla?', 'Yes. Ask for a Bangla explanation whenever a concept is easier to understand in your own language.'],
  ['Can I generate quizzes and notes?', 'Yes. Turn a topic or solved question into focused practice and revision-ready study notes.'],
  ['Is StudyBuddy free?', 'You can start learning with the core StudyBuddy experience for free.'],
]

const loop = [
  ['ASK', 'Bring the question you cannot shake.', MessageCircle],
  ['UNDERSTAND', 'See the reasoning, not just the result.', BrainCircuit],
  ['PRACTICE', 'Turn the idea into active recall.', FileQuestion],
  ['IMPROVE', 'Come back sharper next time.', Trophy],
]

export default function LandingPage() {
  const [openFaq, setOpenFaq] = useState<number | null>(0)
  const [mobileOpen, setMobileOpen] = useState(false)

  return (
    <main className="min-h-screen overflow-hidden bg-[#070B1A] text-[#F8FAFC] selection:bg-[#6C3BFF]/40">
      <style jsx global>{`
        html { scroll-behavior: smooth; }
        @keyframes drift { 0%,100% { transform: translate3d(0,0,0) } 50% { transform: translate3d(0,-10px,0) } }
        @keyframes pulseLine { 0%,100% { opacity:.25; transform:scaleX(.8) } 50% { opacity:1; transform:scaleX(1) } }
        @keyframes blink { 0%,45%,100% { opacity:1 } 50%,95% { opacity:.25 } }
        @keyframes reveal { from { opacity:0; transform:translateY(10px) } to { opacity:1; transform:translateY(0) } }
        .drift { animation: drift 6s ease-in-out infinite; }
        .drift-slow { animation: drift 8s ease-in-out 1s infinite; }
        .reveal { animation: reveal .7s ease-out both; }
        .delay-1 { animation-delay:.15s } .delay-2 { animation-delay:.3s } .delay-3 { animation-delay:.45s }
        @media (prefers-reduced-motion: reduce) { *, *::before, *::after { animation-duration:.01ms !important; scroll-behavior:auto !important; } }
      `}</style>

      <nav className="fixed inset-x-0 top-0 z-50 px-4 pt-4 sm:px-6">
        <div className="mx-auto flex max-w-7xl items-center justify-between rounded-2xl border border-white/10 bg-[#0E1630]/80 px-4 py-3 shadow-2xl shadow-black/20 backdrop-blur-xl sm:px-5">
          <a href="#top" className="flex items-center gap-2.5 font-semibold tracking-tight"><span className="flex size-9 items-center justify-center rounded-xl bg-[#6C3BFF] text-white shadow-lg shadow-[#6C3BFF]/30"><Sparkles size={17} /></span>StudyBuddy</a>
          <div className="hidden items-center gap-7 text-sm text-white/55 md:flex"><a href="#features" className="transition hover:text-white">Features</a><a href="#how" className="transition hover:text-white">How it works</a><a href="#students" className="transition hover:text-white">For students</a><a href="#faq" className="transition hover:text-white">FAQ</a></div>
          <div className="hidden items-center gap-3 md:flex"><Link href="/login" className="px-3 py-2 text-sm font-medium text-white/65 transition hover:text-white">Log in</Link><Link href="/login" className="inline-flex items-center gap-2 rounded-xl bg-[#6C3BFF] px-4 py-2.5 text-sm font-semibold text-white shadow-lg shadow-[#6C3BFF]/25 transition hover:-translate-y-0.5">Start learning free <ArrowRight size={15} /></Link><Link href="/app" className="px-3 py-2 text-sm font-medium text-white/65 transition hover:text-white">Dashboard</Link></div>
          <button aria-label="Open menu" onClick={() => setMobileOpen(!mobileOpen)} className="rounded-lg p-2 md:hidden">{mobileOpen ? <X size={20} /> : <Menu size={20} />}</button>
        </div>
        {mobileOpen && <div className="mx-auto mt-2 flex max-w-7xl flex-col gap-1 rounded-2xl border border-white/10 bg-[#0E1630] p-3 shadow-xl md:hidden"><a onClick={() => setMobileOpen(false)} href="#features" className="rounded-lg px-3 py-2.5 text-sm text-white/75">Features</a><a onClick={() => setMobileOpen(false)} href="#how" className="rounded-lg px-3 py-2.5 text-sm text-white/75">How it works</a><a onClick={() => setMobileOpen(false)} href="#students" className="rounded-lg px-3 py-2.5 text-sm text-white/75">For students</a><a onClick={() => setMobileOpen(false)} href="#faq" className="rounded-lg px-3 py-2.5 text-sm text-white/75">FAQ</a><Link href="/app" className="rounded-lg px-3 py-2.5 text-sm text-white/75">Dashboard</Link><Link href="/login" className="mt-1 rounded-lg bg-[#6C3BFF] px-3 py-2.5 text-center text-sm font-semibold">Start learning free</a></div>}
      </nav>

      <section id="top" className="relative mx-auto max-w-7xl px-5 pb-20 pt-40 sm:px-8 lg:pb-28 lg:pt-48">
        <Network />
        <div className="relative grid items-center gap-14 lg:grid-cols-[.84fr_1.16fr] lg:gap-12">
          <div className="max-w-xl">
            <p className="reveal flex items-center gap-2 text-xs font-semibold tracking-[.22em] text-[#22D3EE]"><span className="size-1.5 rounded-full bg-[#B8FF5A]" /> AI STUDY COMPANION</p>
            <h1 className="reveal delay-1 mt-6 text-balance text-5xl font-bold leading-[.98] tracking-[-.06em] sm:text-7xl lg:text-[5.8rem]">Stop memorizing.<br />Start <span className="bg-gradient-to-r from-[#6C3BFF] via-[#9d7cff] to-[#22D3EE] bg-clip-text text-transparent">understanding.</span></h1>
            <p className="reveal delay-2 mt-7 max-w-lg text-pretty text-lg leading-8 text-white/58">StudyBuddy helps you solve difficult questions, understand the reasoning, practice with AI-generated quizzes, and build better study habits.</p>
            <div className="reveal delay-3 mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/login" className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#6C3BFF] px-5 py-3.5 text-sm font-semibold shadow-xl shadow-[#6C3BFF]/25 transition hover:-translate-y-0.5">Start learning free <ArrowRight size={16} /></Link><Link href="/login" className="inline-flex items-center justify-center gap-2 rounded-xl border border-white/15 bg-white/5 px-5 py-3.5 text-sm font-semibold text-white/85 transition hover:bg-white/10"><Play size={15} className="fill-current text-[#22D3EE]" /> See StudyBuddy in action</Link></div>
            <div className="mt-8 flex flex-wrap gap-x-5 gap-y-2 text-xs text-white/42"><span>Questions</span><span className="text-[#6C3BFF]">•</span><span>Tutor</span><span className="text-[#22D3EE]">•</span><span>Quizzes</span><span className="text-[#B8FF5A]">•</span><span>Notes</span></div>
          </div>
          <DemoWorkspace />
        </div>
      </section>

      <section className="border-y border-white/10 bg-[#0E1630]/70"><div className="mx-auto grid max-w-7xl gap-6 px-5 py-7 sm:grid-cols-3 sm:px-8"><Value icon={BrainCircuit} title="Understand, don't memorize" text="Step-by-step reasoning that stays with you." /><Value icon={Languages} title="English + Bangla" text="Learn in the language that unlocks the idea." /><Value icon={Target} title="Made for momentum" text="Small wins that become a real study habit." /></div></section>

      <section id="how" className="relative mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:py-32"><div className="max-w-2xl"><p className="text-xs font-semibold tracking-[.22em] text-[#22D3EE]">THE STUDYBUDDY LOOP</p><h2 className="mt-4 text-balance text-4xl font-bold tracking-[-.05em] sm:text-6xl">One question.<br /><span className="text-white/45">A better study session.</span></h2></div><div className="relative mt-16 grid gap-4 md:grid-cols-4">{loop.map(([title, text, Icon], i) => { const StageIcon = Icon as typeof BrainCircuit; return <div key={title} className="relative border-t border-white/15 pt-5 md:border-t-0 md:border-l md:pl-6"><div className={`flex size-11 items-center justify-center rounded-xl ${i === 0 ? 'bg-[#6C3BFF]' : 'bg-white/5'} text-[#22D3EE]`}><StageIcon size={19} /></div><p className="mt-7 text-xs font-semibold tracking-[.2em] text-[#B8FF5A]">0{i + 1} / {title}</p><p className="mt-3 max-w-[14rem] text-lg font-semibold leading-7">{text}</p>{i < 3 && <div className="absolute right-[-1.1rem] top-5 hidden h-px w-8 origin-left bg-gradient-to-r from-[#6C3BFF] to-[#22D3EE] md:block" />}</div> })}</div></section>

      <section className="border-y border-white/10 bg-[#0E1630]/60"><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 py-24 sm:px-8 lg:grid-cols-2 lg:py-32"><div><p className="text-xs font-semibold tracking-[.22em] text-[#22D3EE]">THE PROBLEM</p><h2 className="mt-4 text-balance text-4xl font-bold tracking-[-.05em] sm:text-5xl">Getting an answer is easy.<br /><span className="text-white/40">Understanding it is harder.</span></h2><p className="mt-6 max-w-md leading-7 text-white/55">Search results give you somewhere to stop. StudyBuddy gives you a reason to keep going.</p></div><div className="grid gap-4 sm:grid-cols-2"><Compare title="Search" items={['Copy', 'Forget']} muted /><Compare title="StudyBuddy" items={['Understand', 'Practice', 'Remember']} /></div></div></section>

      <section id="features" className="mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:py-32"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="text-xs font-semibold tracking-[.22em] text-[#B8FF5A]">THE EXPERIENCE</p><h2 className="mt-4 text-balance text-4xl font-bold tracking-[-.05em] sm:text-6xl">One question can become<br /><span className="text-white/40">a complete study session.</span></h2></div><p className="max-w-sm leading-7 text-white/50">Solve it. Ask why. Practice it. Keep the insight for later.</p></div><ProductCanvas /></section>

      <section className="border-y border-white/10 bg-gradient-to-br from-[#27126b] via-[#101a42] to-[#071c2d]"><div className="mx-auto grid max-w-7xl items-center gap-14 px-5 py-24 sm:px-8 lg:grid-cols-2 lg:py-32"><div><p className="text-xs font-semibold tracking-[.22em] text-[#B8FF5A]">AI TUTOR</p><h2 className="mt-4 text-balance text-4xl font-bold tracking-[-.05em] sm:text-6xl">Don't stop at the answer.<br /><span className="text-[#22D3EE]">Ask why.</span></h2><p className="mt-6 max-w-md leading-7 text-white/60">Follow the thread until the idea feels like yours. No judgment, no rushed explanation.</p><div className="mt-8 flex flex-wrap gap-2">{['Explain simply', 'Give me an example', 'Teach step by step', 'Quiz me', 'Explain in Bangla'].map(x => <span key={x} className="rounded-full border border-white/15 bg-white/5 px-3 py-2 text-xs text-white/75">{x}</span>)}</div></div><TutorChat /></div></section>

      <section id="students" className="mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:py-32"><div className="max-w-2xl"><p className="text-xs font-semibold tracking-[.22em] text-[#22D3EE]">FOR STUDENTS IN BANGLADESH</p><h2 className="mt-4 text-balance text-4xl font-bold tracking-[-.05em] sm:text-6xl">Built for your<br /><span className="text-white/40">study journey.</span></h2><p className="mt-6 max-w-xl text-lg leading-8 text-white/55">Whether you're preparing for board exams or navigating university coursework, StudyBuddy gives you one place to ask, learn, practice, and review.</p></div><div className="mt-14 grid gap-4 md:grid-cols-3"><Path title="SSC" text="Build foundations that make the next chapter easier." /><Path title="HSC" text="Go deeper on the concepts that exams demand." /><Path title="University" text="Untangle coursework and keep your momentum." /></div></section>

      <section className="border-y border-white/10 bg-[#0E1630]/70"><div className="mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:py-32"><p className="text-center text-xs font-semibold tracking-[.22em] text-[#B8FF5A]">THE DIFFERENCE</p><h2 className="mx-auto mt-4 max-w-3xl text-center text-balance text-4xl font-bold tracking-[-.05em] sm:text-6xl">Not just answers.<br /><span className="bg-gradient-to-r from-[#6C3BFF] to-[#22D3EE] bg-clip-text text-transparent">Understanding.</span></h2><div className="mx-auto mt-16 grid max-w-4xl gap-4 md:grid-cols-2"><Difference title="Other tools" items={['Answer']} muted /><Difference title="StudyBuddy" items={['Answer', 'Explanation', 'Bangla explanation', 'Key concept', 'Common mistake', 'Follow-up']} /></div></div></section>

      <section className="mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:py-32"><div className="overflow-hidden rounded-3xl border border-white/10 bg-[#0E1630] shadow-2xl shadow-[#6C3BFF]/10"><div className="flex items-center justify-between border-b border-white/10 px-5 py-4"><Link href="/app" className="flex items-center gap-2 text-sm font-semibold"><Sparkles size={16} className="text-[#22D3EE]" /> Open StudyBuddy</Link><span className="rounded-full bg-[#B8FF5A]/10 px-3 py-1 text-[10px] font-semibold text-[#B8FF5A]">READY TO LEARN</span></div><div className="grid min-h-[330px] md:grid-cols-[180px_1fr]"><aside className="hidden border-r border-white/10 p-4 md:block">{['Dashboard', 'Solve Question', 'AI Tutor', 'Quiz', 'Study Notes', 'History', 'Mistakes', 'Progress'].map((x, i) => <div key={x} className={`mb-1 rounded-lg px-3 py-2 text-xs ${i === 1 ? 'bg-[#6C3BFF]/20 text-[#22D3EE]' : 'text-white/40'}`}>{x}</div>)}</aside><div className="p-6 sm:p-10"><p className="text-xs uppercase tracking-[.2em] text-white/35">Today's focus</p><h3 className="mt-3 text-2xl font-semibold">Newton's laws of motion</h3><div className="mt-7 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-white/10 bg-white/[.03] p-4"><Zap size={17} className="text-[#B8FF5A]" /><p className="mt-8 text-2xl font-bold">12</p><p className="mt-1 text-xs text-white/40">questions solved</p></div><div className="rounded-2xl border border-white/10 bg-white/[.03] p-4"><Target size={17} className="text-[#22D3EE]" /><p className="mt-8 text-2xl font-bold">78%</p><p className="mt-1 text-xs text-white/40">concept clarity</p></div><div className="rounded-2xl border border-white/10 bg-white/[.03] p-4"><Trophy size={17} className="text-[#6C3BFF]" /><p className="mt-8 text-2xl font-bold">4 day</p><p className="mt-1 text-xs text-white/40">learning streak</p></div></div></div></div></div></section>

      <section id="faq" className="border-t border-white/10 bg-[#0E1630]/60"><div className="mx-auto max-w-3xl px-5 py-24 sm:px-8 lg:py-32"><p className="text-center text-xs font-semibold tracking-[.22em] text-[#22D3EE]">FAQ</p><h2 className="mt-4 text-center text-4xl font-bold tracking-[-.05em] sm:text-5xl">Questions, answered.</h2><div className="mt-12 divide-y divide-white/10 rounded-2xl border border-white/10">{faqs.map(([q, a], i) => <div key={q} className="px-5 sm:px-6"><button className="flex w-full items-center justify-between gap-4 py-5 text-left font-semibold" onClick={() => setOpenFaq(openFaq === i ? null : i)}><span>{q}</span><ChevronDown size={18} className={`shrink-0 text-white/40 transition-transform ${openFaq === i ? 'rotate-180 text-[#22D3EE]' : ''}`} /></button>{openFaq === i && <p className="pb-5 pr-8 text-sm leading-7 text-white/50">{a}</p>}</div>)}</div></div></section>

      <section className="px-5 py-20 sm:px-8"><div className="relative mx-auto max-w-7xl overflow-hidden rounded-3xl border border-[#6C3BFF]/30 bg-gradient-to-br from-[#27126b] via-[#111c44] to-[#071c2d] px-6 py-20 text-center sm:px-12"><div className="absolute left-1/2 top-0 size-72 -translate-x-1/2 -translate-y-1/2 rounded-full bg-[#22D3EE]/15 blur-3xl" /><Sparkles className="relative mx-auto text-[#B8FF5A]" size={25} /><h2 className="relative mx-auto mt-5 max-w-2xl text-balance text-4xl font-bold tracking-[-.05em] sm:text-6xl">Your next study session starts here.</h2><p className="relative mx-auto mt-5 max-w-xl text-base leading-7 text-white/60">Ask a question. Understand the answer. Keep learning.</p><Link href="/login" className="relative mt-8 inline-flex items-center gap-2 rounded-xl bg-[#B8FF5A] px-5 py-3.5 text-sm font-bold text-[#070B1A] transition hover:-translate-y-0.5">Start learning free <ArrowRight size={16} /></a></div></section>

      <footer className="border-t border-white/10"><div className="mx-auto flex max-w-7xl flex-col gap-8 px-5 py-10 sm:px-8 md:flex-row md:items-center md:justify-between"><div><a href="#top" className="flex items-center gap-2 font-semibold"><span className="flex size-8 items-center justify-center rounded-lg bg-[#6C3BFF] text-white"><Sparkles size={15} /></span>StudyBuddy</a><p className="mt-2 text-sm text-white/40">AI-powered study support for students.</p></div><div className="flex flex-wrap gap-5 text-sm text-white/45"><a href="#features" className="hover:text-white">Features</a><a href="#how" className="hover:text-white">How it works</a><Link href="/login" className="hover:text-white">Login</Link><a href="/privacy" className="hover:text-white">Privacy</a><a href="/terms" className="hover:text-white">Terms</a></div><p className="text-xs text-white/30">© 2026 StudyBuddy</p></div></footer>
    </main>
  )
}

function Network() { return <div aria-hidden className="pointer-events-none absolute inset-0 -z-10 opacity-60"><div className="absolute right-[8%] top-20 size-72 rounded-full bg-[#6C3BFF]/15 blur-3xl" /><div className="absolute left-[30%] top-44 size-56 rounded-full bg-[#22D3EE]/10 blur-3xl" /><svg className="absolute right-0 top-24 h-[500px] w-[65%] opacity-40" viewBox="0 0 700 500" fill="none"><path d="M40 240 190 120l120 100 150-150 190 120M190 120l-30 220 150-120 80 180 120-230" stroke="url(#net)" strokeDasharray="3 12" /><circle cx="190" cy="120" r="4" fill="#22D3EE" /><circle cx="310" cy="220" r="4" fill="#B8FF5A" /><circle cx="460" cy="70" r="4" fill="#6C3BFF" /><circle cx="390" cy="400" r="4" fill="#22D3EE" /><defs><linearGradient id="net"><stop stopColor="#6C3BFF" /><stop offset="1" stopColor="#22D3EE" /></linearGradient></defs></svg></div> }
function DemoWorkspace() { return <div className="drift relative mx-auto w-full max-w-xl"><div className="absolute -inset-8 -z-10 rounded-full bg-[#6C3BFF]/20 blur-3xl" /><div className="rounded-3xl border border-white/15 bg-[#0E1630]/90 p-3 shadow-2xl shadow-[#6C3BFF]/20 sm:p-4"><div className="flex items-center gap-2 border-b border-white/10 px-2 pb-3"><span className="size-2 rounded-full bg-[#B8FF5A]" /><span className="ml-3 text-xs text-white/35">StudyBuddy / Solve Question</span><span className="ml-auto flex items-center gap-1 text-[10px] text-[#B8FF5A]"><span className="size-1.5 animate-pulse rounded-full bg-[#B8FF5A]" /> AI online</span></div><div className="grid gap-4 p-3 sm:grid-cols-[.8fr_1.2fr] sm:p-5"><div className="rounded-2xl bg-white/[.06] p-4"><div className="flex items-center justify-between"><span className="text-xs font-semibold text-[#22D3EE]">Physics</span><span className="rounded-md bg-white/10 px-2 py-1 text-[10px] text-white/45">SSC</span></div><p className="mt-5 text-sm font-semibold leading-6">What is Newton's Second Law?</p><div className="mt-6 flex items-center gap-2 text-xs text-white/35"><Upload size={13} /> Add screenshot</div><Link href="/login" className="mt-6 flex w-full items-center justify-center rounded-lg bg-[#6C3BFF] py-2.5 text-xs font-semibold">Try Question Solver <ArrowRight className="ml-1 inline" size={13} /></Link></div><div className="rounded-2xl border border-white/10 p-4"><div className="flex items-center gap-2 text-xs font-semibold text-[#22D3EE]"><Sparkles size={14} /> AI result</div><p className="mt-5 text-xs uppercase tracking-wider text-white/35">Answer</p><p className="mt-2 text-xl font-bold">F = ma</p><div className="mt-5 border-t border-white/10 pt-4"><p className="text-xs uppercase tracking-wider text-white/35">Explanation</p><p className="mt-2 text-xs leading-5 text-white/55">The force on an object is equal to its mass multiplied by its acceleration.</p></div><div className="mt-5 rounded-xl bg-[#22D3EE]/10 p-3"><p className="text-[10px] font-semibold text-[#22D3EE]">BANGLA EXPLANATION</p><p className="mt-1 text-xs text-white/70">বল = ভর × ত্বরণ</p></div></div></div></div><div className="drift-slow absolute -right-6 top-16 hidden rounded-xl border border-white/10 bg-[#0E1630] px-3 py-2 text-xs shadow-xl sm:block"><span className="mr-2 text-[#B8FF5A]">●</span>3 key concepts</div><div className="drift-slow absolute -bottom-5 -left-6 hidden rounded-xl border border-white/10 bg-[#0E1630] px-3 py-2 text-xs shadow-xl sm:block"><span className="mr-2 text-[#22D3EE]">✦</span>Quiz ready</div></div> }
function Value({ icon: Icon, title, text }: { icon: typeof BrainCircuit; title: string; text: string }) { return <div className="flex gap-3"><Icon className="mt-0.5 shrink-0 text-[#22D3EE]" size={20} /><div><p className="text-sm font-semibold">{title}</p><p className="mt-1 text-xs leading-5 text-white/45">{text}</p></div></div> }
function Compare({ title, items, muted = false }: { title: string; items: string[]; muted?: boolean }) { return <div className={`rounded-2xl border p-6 ${muted ? 'border-white/10 bg-white/[.02] text-white/35' : 'border-[#6C3BFF]/40 bg-[#6C3BFF]/10'}`}><p className="text-xs font-semibold uppercase tracking-[.2em]">{title}</p><div className="mt-6 flex flex-col gap-4">{items.map((x, i) => <div key={x} className="flex items-center gap-3 text-lg font-semibold"><span className={`size-2 rounded-full ${muted ? 'bg-white/20' : i === items.length - 1 ? 'bg-[#B8FF5A]' : 'bg-[#22D3EE]'}`} />{x}</div>)}</div></div> }
function ProductCanvas() { return <div className="mt-14 rounded-3xl border border-white/10 bg-[#0E1630] p-4 shadow-2xl shadow-[#6C3BFF]/10 sm:p-6"><div className="grid gap-4 md:grid-cols-[1.1fr_.9fr]"><div className="rounded-2xl bg-white/[.04] p-6"><div className="flex items-center justify-between"><p className="text-xs font-semibold text-[#22D3EE]">QUESTION SOLVER</p><span className="text-[10px] text-white/35">Physics / HSC</span></div><h3 className="mt-8 max-w-md text-2xl font-semibold leading-9">Why does a ball slow down when it rolls across the floor?</h3><div className="mt-8 flex items-center gap-2 rounded-xl border border-white/10 bg-black/10 px-3 py-3 text-xs text-white/35"><MessageCircle size={15} /> Ask a follow-up question...</div></div><div className="rounded-2xl border border-white/10 p-6"><p className="flex items-center gap-2 text-xs font-semibold text-[#B8FF5A]"><Sparkles size={14} /> UNDERSTAND</p><p className="mt-8 text-sm leading-7 text-white/65">Friction acts opposite to the direction of motion, converting some of the ball's kinetic energy into heat.</p><div className="mt-8 rounded-xl bg-[#6C3BFF]/15 p-4"><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-[#22D3EE]">NEXT STEP</p><p className="mt-2 text-sm font-semibold">Generate a quiz on friction <ArrowRight className="ml-1 inline text-[#B8FF5A]" size={14} /></p></div></div></div></div> }
function TutorChat() { return <div className="rounded-3xl border border-white/15 bg-[#070B1A]/60 p-5 shadow-xl sm:p-7"><div className="flex items-center gap-3 border-b border-white/10 pb-5"><span className="flex size-9 items-center justify-center rounded-xl bg-[#6C3BFF]"><Sparkles size={16} /></span><div><p className="text-sm font-semibold">StudyBuddy Tutor</p><p className="text-[10px] text-white/40">Explaining step by step</p></div></div><div className="mt-6 flex flex-col gap-4 text-sm"><div className="self-end rounded-2xl rounded-br-sm bg-white/10 px-4 py-3 text-white/75">I still don't understand this.</div><div className="max-w-[90%] rounded-2xl rounded-bl-sm bg-[#6C3BFF]/25 px-4 py-3 leading-6">Let's break it down step by step. Think of force as a push or pull that changes motion.</div><div className="flex flex-wrap gap-2 pt-2">{['Give me an example', 'Explain in Bangla'].map(x => <span key={x} className="rounded-lg border border-white/10 px-3 py-2 text-[11px] text-white/55">{x}</span>)}</div></div></div> }
function Difference({ title, items, muted = false }: { title: string; items: string[]; muted?: boolean }) { return <div className={`rounded-2xl border p-6 ${muted ? 'border-white/10 bg-black/10 text-white/35' : 'border-[#22D3EE]/30 bg-gradient-to-br from-[#6C3BFF]/20 to-[#22D3EE]/10'}`}><p className="text-xs font-semibold uppercase tracking-[.2em]">{title}</p><div className="mt-6 grid gap-3 sm:grid-cols-2">{items.map(x => <div key={x} className="flex items-center gap-2 text-sm font-medium"><Check size={15} className={muted ? 'text-white/20' : 'text-[#B8FF5A]'} />{x}</div>)}</div></div> }
function Path({ title, text }: { title: string; text: string }) { return <div className="group rounded-2xl border border-white/10 bg-white/[.03] p-6 transition hover:-translate-y-1 hover:border-[#6C3BFF]/60"><div className="flex items-center justify-between"><span className="text-4xl font-bold tracking-[-.06em] text-white/90">{title}</span><ArrowRight size={18} className="text-[#22D3EE] transition group-hover:translate-x-1" /></div><p className="mt-10 max-w-xs text-sm leading-6 text-white/45">{text}</p></div> }
function Step({ n, title, text }: { n: string; title: string; text: string }) { return <div className="border-t-2 border-[#6C3BFF] pt-5"><span className="font-mono text-sm font-semibold text-[#22D3EE]">{n}</span><h3 className="mt-5 text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-white/50">{text}</p></div> }

void Step
void CircleHelp
void Check
void Zap
