'use client'

import { useState } from 'react'
import { ArrowRight, BarChart3, BrainCircuit, Check, ChevronDown, CircleHelp, FileQuestion, Languages, Menu, MessageCircle, Play, Sparkles, Target, Trophy, Upload, X, Zap } from 'lucide-react'

const faqs = [
  ['Is StudyBuddy free to use?', 'Yes. You can start with the core study tools for free and build a daily learning habit without a subscription.'],
  ['Can it explain questions in Bangla?', 'Absolutely. StudyBuddy is built for Bangladesh students, with clear English and Bangla explanations whenever you need them.'],
  ['Which subjects are supported?', 'Start with Physics, Mathematics, Chemistry, Biology, and any text-based question from your SSC, HSC, or university syllabus.'],
  ['Is my study history private?', 'Yes. Your account history is private and protected by Supabase authentication.'],
]

export default function LandingPage() {
  const [openFaq, setOpenFaq] = useState<number | null>(0)
  const [mobileOpen, setMobileOpen] = useState(false)

  return (
    <main className="overflow-hidden bg-background text-foreground">
      <nav className="fixed inset-x-0 top-0 z-50 px-4 pt-4 sm:px-6">
        <div className="mx-auto flex max-w-6xl items-center justify-between rounded-2xl border border-border/70 bg-card/90 px-4 py-3 shadow-sm backdrop-blur-xl sm:px-5">
          <a href="#top" className="flex items-center gap-2.5 font-semibold tracking-tight"><span className="flex size-9 items-center justify-center rounded-xl bg-primary text-primary-foreground"><Sparkles size={17} /></span>StudyBuddy</a>
          <div className="hidden items-center gap-7 text-sm text-muted-foreground md:flex"><a href="#product" className="hover:text-foreground">Product</a><a href="#how" className="hover:text-foreground">How it works</a><a href="#faq" className="hover:text-foreground">FAQ</a></div>
          <div className="hidden items-center gap-3 md:flex"><a href="/auth/login" className="px-3 py-2 text-sm font-medium text-muted-foreground hover:text-foreground">Log in</a><a href="/auth/sign-up" className="inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground">Get started <ArrowRight size={15} /></a></div>
          <button aria-label="Open menu" onClick={() => setMobileOpen(!mobileOpen)} className="rounded-lg p-2 md:hidden">{mobileOpen ? <X size={20} /> : <Menu size={20} />}</button>
        </div>
        {mobileOpen && <div className="mx-auto mt-2 flex max-w-6xl flex-col gap-1 rounded-2xl border border-border bg-card p-3 shadow-lg md:hidden"><a onClick={() => setMobileOpen(false)} href="#product" className="rounded-lg px-3 py-2 text-sm">Product</a><a onClick={() => setMobileOpen(false)} href="#how" className="rounded-lg px-3 py-2 text-sm">How it works</a><a onClick={() => setMobileOpen(false)} href="#faq" className="rounded-lg px-3 py-2 text-sm">FAQ</a><a href="/auth/login" className="mt-1 rounded-lg bg-primary px-3 py-2.5 text-center text-sm font-semibold text-primary-foreground">Start learning</a></div>}
      </nav>

      <section id="top" className="relative mx-auto max-w-6xl px-5 pb-20 pt-40 sm:px-8 lg:pb-28 lg:pt-48">
        <div className="grid items-center gap-14 lg:grid-cols-[0.9fr_1.1fr] lg:gap-16">
          <div className="max-w-xl">
            <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/5 px-3 py-1.5 text-xs font-semibold text-primary"><span className="size-1.5 rounded-full bg-primary" /> Built for students in Bangladesh</div>
            <h1 className="text-balance text-5xl font-bold tracking-[-0.05em] sm:text-6xl lg:text-7xl">Study smarter.<br /><span className="text-primary">Feel ready.</span></h1>
            <p className="mt-6 max-w-lg text-pretty text-lg leading-8 text-muted-foreground">Your AI study companion for turning confusing questions into clear understanding — one thoughtful step at a time.</p>
            <div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="/auth/sign-up" className="inline-flex items-center justify-center gap-2 rounded-xl bg-primary px-5 py-3.5 text-sm font-semibold text-primary-foreground shadow-lg shadow-primary/15">Start learning free <ArrowRight size={16} /></a><a href="#product" className="inline-flex items-center justify-center gap-2 rounded-xl border border-border bg-card px-5 py-3.5 text-sm font-semibold"><Play size={15} className="fill-current" /> See how it works</a></div>
            <div className="mt-8 flex flex-wrap items-center gap-x-5 gap-y-2 text-xs text-muted-foreground"><span className="flex items-center gap-1.5"><Check size={14} className="text-primary" /> No credit card</span><span className="flex items-center gap-1.5"><Check size={14} className="text-primary" /> English + Bangla</span><span className="flex items-center gap-1.5"><Check size={14} className="text-primary" /> SSC to university</span></div>
          </div>
          <DemoWorkspace />
        </div>
      </section>

      <div className="border-y border-border bg-card/60"><div className="mx-auto grid max-w-6xl gap-6 px-5 py-6 sm:grid-cols-3 sm:px-8"><Value icon={BrainCircuit} title="Understand, don't memorize" text="Step-by-step explanations that actually stick." /><Value icon={Languages} title="Made for your context" text="Clear learning in English or Bangla." /><Value icon={Target} title="Build your momentum" text="Small wins that become a real habit." /></div></div>

      <section id="product" className="mx-auto max-w-6xl px-5 py-24 sm:px-8 lg:py-32"><div className="max-w-2xl"><p className="text-sm font-semibold text-primary">A better way to study</p><h2 className="mt-3 text-balance text-4xl font-bold tracking-[-0.04em] sm:text-5xl">Everything you need to make progress.</h2><p className="mt-5 text-lg leading-8 text-muted-foreground">Not another answer machine. StudyBuddy helps you build the understanding and confidence to solve the next question on your own.</p></div><div className="mt-14 grid gap-5 lg:grid-cols-2"><FeatureCard icon={BrainCircuit} eyebrow="01 / Understand" title="Solve the question in front of you." text="Type it, paste it, or upload a screenshot. Get a clear answer with the reasoning behind it, not just a final number." className="bg-primary text-primary-foreground" /><FeatureCard icon={MessageCircle} eyebrow="02 / Go deeper" title="Ask the follow-up that is on your mind." text="Keep the conversation going with an AI tutor that meets you where you are and explains things simply." /><FeatureCard icon={FileQuestion} eyebrow="03 / Practice" title="Turn understanding into recall." text="Generate focused quizzes on any topic, then see exactly where your thinking needs more work." /><FeatureCard icon={BarChart3} eyebrow="04 / Keep going" title="See your progress become visible." text="Your history, mistakes, and small wins come together to make your next study session more intentional." /></div></section>

      <section className="bg-muted/60"><div className="mx-auto grid max-w-6xl items-center gap-14 px-5 py-24 sm:px-8 lg:grid-cols-2 lg:py-32"><div><p className="text-sm font-semibold text-primary">For the way you learn</p><h2 className="mt-3 text-balance text-4xl font-bold tracking-[-0.04em] sm:text-5xl">The help you wish you had at 11pm.</h2><p className="mt-5 text-lg leading-8 text-muted-foreground">When the textbook feels too dense and the group chat is quiet, StudyBuddy is there to make the next step feel possible.</p><div className="mt-8 flex flex-col gap-4"><Bullet text="Explanations that match your education level" /><Bullet text="Bangla support when English gets in the way" /><Bullet text="A private notebook for every question you solve" /><Bullet text="Practice that focuses on your actual weak spots" /></div></div><div className="relative rounded-3xl border border-border bg-card p-5 shadow-xl shadow-primary/5 sm:p-7"><div className="mb-5 flex items-center justify-between"><div className="flex items-center gap-2 text-sm font-semibold"><span className="flex size-8 items-center justify-center rounded-lg bg-primary text-primary-foreground"><Sparkles size={15} /></span>Study session</div><span className="rounded-full bg-primary/10 px-2.5 py-1 text-xs font-medium text-primary">Today</span></div><div className="rounded-2xl border border-border bg-background p-5"><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Your focus</p><h3 className="mt-2 text-xl font-bold">Newton's second law</h3><div className="mt-5 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full w-3/4 rounded-full bg-primary" /></div><div className="mt-2 flex justify-between text-xs text-muted-foreground"><span>3 of 4 questions</span><span>75%</span></div></div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-primary/10 p-4"><Trophy size={18} className="text-primary" /><p className="mt-3 text-2xl font-bold">12</p><p className="text-xs text-muted-foreground">Questions solved</p></div><div className="rounded-2xl bg-muted p-4"><Zap size={18} className="text-primary" /><p className="mt-3 text-2xl font-bold">4 day</p><p className="text-xs text-muted-foreground">Study streak</p></div></div></div></div></section>

      <section id="how" className="mx-auto max-w-6xl px-5 py-24 sm:px-8 lg:py-32"><div className="text-center"><p className="text-sm font-semibold text-primary">Simple by design</p><h2 className="mt-3 text-4xl font-bold tracking-[-0.04em] sm:text-5xl">From stuck to steady.</h2></div><div className="mt-14 grid gap-10 md:grid-cols-3"><Step n="01" title="Bring your question" text="Start with the thing you don't understand. No perfect wording required." /><Step n="02" title="Learn the why" text="Get an explanation in the language and level that works for you." /><Step n="03" title="Make it yours" text="Ask follow-ups, take a quiz, and come back stronger next time." /></div></section>

      <section id="faq" className="bg-card"><div className="mx-auto max-w-3xl px-5 py-24 sm:px-8 lg:py-32"><div className="text-center"><CircleHelp className="mx-auto text-primary" size={28} /><h2 className="mt-4 text-4xl font-bold tracking-[-0.04em]">Questions, answered.</h2></div><div className="mt-12 divide-y divide-border rounded-2xl border border-border">{faqs.map(([q, a], index) => <div key={q} className="px-5 sm:px-6"><button onClick={() => setOpenFaq(openFaq === index ? null : index)} className="flex w-full items-center justify-between gap-4 py-5 text-left font-semibold"><span>{q}</span><ChevronDown size={18} className={`shrink-0 text-muted-foreground transition-transform ${openFaq === index ? 'rotate-180' : ''}`} /></button>{openFaq === index && <p className="pb-5 pr-8 text-sm leading-7 text-muted-foreground">{a}</p>}</div>)}</div></div></section>

      <section className="px-5 py-20 sm:px-8"><div className="mx-auto max-w-6xl overflow-hidden rounded-3xl bg-primary px-6 py-16 text-center text-primary-foreground sm:px-12"><Sparkles className="mx-auto opacity-70" size={25} /><h2 className="mx-auto mt-5 max-w-2xl text-balance text-4xl font-bold tracking-[-0.04em] sm:text-5xl">Your next breakthrough starts with one question.</h2><p className="mx-auto mt-5 max-w-xl text-base leading-7 text-primary-foreground/75">Join students building a calmer, clearer way to learn.</p><a href="/auth/sign-up" className="mt-8 inline-flex items-center gap-2 rounded-xl bg-primary-foreground px-5 py-3.5 text-sm font-semibold text-primary">Start learning free <ArrowRight size={16} /></a></div></section>

      <footer className="border-t border-border"><div className="mx-auto flex max-w-6xl flex-col gap-8 px-5 py-10 sm:px-8 md:flex-row md:items-center md:justify-between"><div><a href="#top" className="flex items-center gap-2 font-semibold"><span className="flex size-8 items-center justify-center rounded-lg bg-primary text-primary-foreground"><Sparkles size={15} /></span>StudyBuddy</a><p className="mt-2 text-sm text-muted-foreground">Learn smarter, not harder.</p></div><div className="flex flex-wrap gap-5 text-sm text-muted-foreground"><a href="#product" className="hover:text-foreground">Product</a><a href="#faq" className="hover:text-foreground">FAQ</a><a href="/privacy" className="hover:text-foreground">Privacy</a><a href="/terms" className="hover:text-foreground">Terms</a></div><p className="text-xs text-muted-foreground">© 2026 StudyBuddy</p></div></footer>
    </main>
  )
}

function DemoWorkspace() { return <div className="relative mx-auto w-full max-w-xl"><div className="absolute -inset-6 -z-10 rounded-full bg-primary/10 blur-3xl" /><div className="rounded-3xl border border-border bg-card p-3 shadow-2xl shadow-primary/10 sm:p-4"><div className="flex items-center gap-2 border-b border-border px-2 pb-3"><span className="size-2 rounded-full bg-destructive/60" /><span className="size-2 rounded-full bg-amber/70" /><span className="size-2 rounded-full bg-primary/60" /><span className="ml-3 text-xs text-muted-foreground">StudyBuddy / Solve Question</span></div><div className="grid gap-4 p-3 sm:grid-cols-[0.8fr_1.2fr] sm:p-5"><div className="rounded-2xl bg-muted p-4"><div className="flex items-center justify-between"><span className="text-xs font-semibold text-primary">Physics</span><span className="rounded-md bg-card px-2 py-1 text-[10px] text-muted-foreground">SSC</span></div><p className="mt-5 text-sm font-semibold leading-6">What is the acceleration of a 2kg object when a force of 10N acts on it?</p><div className="mt-5 flex items-center gap-2 text-xs text-muted-foreground"><Upload size={13} /> Add screenshot</div><button className="mt-6 w-full rounded-lg bg-primary py-2.5 text-xs font-semibold text-primary-foreground">Solve with AI <ArrowRight className="ml-1 inline" size={13} /></button></div><div className="rounded-2xl border border-border p-4"><div className="flex items-center gap-2 text-xs font-semibold text-primary"><Sparkles size={14} /> AI result</div><p className="mt-5 text-xs font-semibold uppercase tracking-wider text-muted-foreground">Answer</p><p className="mt-2 text-xl font-bold">5 m/s²</p><div className="mt-5 border-t border-border pt-4"><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Explanation</p><p className="mt-2 text-xs leading-5 text-muted-foreground">Using Newton's second law: force equals mass times acceleration. So acceleration is 10 ÷ 2 = 5 m/s².</p></div><div className="mt-5 rounded-lg bg-primary/10 px-3 py-2 text-xs text-primary">Ask a follow-up →</div></div></div></div></div> }
function Value({ icon: Icon, title, text }: { icon: typeof BrainCircuit; title: string; text: string }) { return <div className="flex gap-3"><Icon className="mt-0.5 shrink-0 text-primary" size={20} /><div><p className="text-sm font-semibold">{title}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{text}</p></div></div> }
function FeatureCard({ icon: Icon, eyebrow, title, text, className = '' }: { icon: typeof BrainCircuit; eyebrow: string; title: string; text: string; className?: string }) { return <div className={`min-h-64 rounded-3xl border border-border p-7 ${className || 'bg-card'}`}><Icon size={23} /><p className="mt-12 text-xs font-semibold uppercase tracking-widest opacity-60">{eyebrow}</p><h3 className="mt-3 max-w-md text-2xl font-bold tracking-tight">{title}</h3><p className="mt-3 max-w-md text-sm leading-6 opacity-70">{text}</p></div> }
function Bullet({ text }: { text: string }) { return <div className="flex items-center gap-3 text-sm"><span className="flex size-5 items-center justify-center rounded-full bg-primary/10 text-primary"><Check size={13} /></span>{text}</div> }
function Step({ n, title, text }: { n: string; title: string; text: string }) { return <div className="relative border-t-2 border-primary pt-5"><span className="font-mono text-sm font-semibold text-primary">{n}</span><h3 className="mt-5 text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p></div> }

