'use client'

import Link from 'next/link'
import { FormEvent, useState } from 'react'
import { createClient } from '@/lib/supabase/client'

export default function SignUpPage() { const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(''); setMessage(''); const { data, error } = await createClient().auth.signUp({ email, password, options: { emailRedirectTo: process.env.NEXT_PUBLIC_DEV_SUPABASE_REDIRECT_URL || `${window.location.origin}/auth/callback`, data: { full_name: name } } }); if (error) setError(error.message.toLowerCase().includes('password') ? 'Choose a stronger password.' : 'Unable to create this account. Please check your details.'); else setMessage(data.session ? 'Account created. You can now continue.' : 'Account created. Check your email to confirm your account.'); setLoading(false) }
  return <main className="flex min-h-screen items-center justify-center bg-background px-5 py-10 text-foreground"><section className="w-full max-w-md rounded-2xl border border-border bg-card p-7 shadow-sm"><div className="mb-8 flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-xl bg-primary text-primary-foreground">S</div><span className="font-semibold">StudyBuddy</span></div><h1 className="text-3xl font-bold tracking-tight">Create your account</h1><p className="mt-2 text-sm text-muted-foreground">Start learning smarter with your personal study companion.</p><form onSubmit={submit} className="mt-7 flex flex-col gap-4"><Field label="Name" type="text" value={name} onChange={setName} /><Field label="Email" type="email" value={email} onChange={setEmail} /><Field label="Password" type="password" value={password} onChange={setPassword} />{error && <p role="alert" className="text-sm text-destructive">{error}</p>}{message && <p role="status" className="text-sm text-primary">{message}</p>}<button disabled={loading} className="rounded-xl bg-primary py-3 font-semibold text-primary-foreground disabled:opacity-50">{loading ? 'Creating account…' : 'Sign up'}</button></form><p className="mt-6 text-center text-sm text-muted-foreground">Already have an account? <Link className="font-semibold text-primary" href="/auth/login">Log in</Link></p></section></main> }
function Field({ label, type, value, onChange }: { label: string; type: string; value: string; onChange: (value: string) => void }) { return <label className="flex flex-col gap-2 text-sm font-medium">{label}<input required type={type} minLength={type === 'password' ? 6 : undefined} value={value} onChange={(e) => onChange(e.target.value)} className="rounded-xl border border-input bg-background px-4 py-3 font-normal outline-none focus:border-primary" /></label> }
